BlogBundle\Entity\Post:
    type: entity
    table: post
    repositoryClass: BlogBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            unique: true
        content:
            type: text
            nullable: true
#        author:
#            type: object
#            nullable: true
#        seo:
#            type: object
#            nullable: true
#        tags:
#            type: object
#            nullable: true
        publishedAt:
            type: datetime
    manyToOne:
        author:
            targetEntity: BlogBundle\Entity\Author 
            joinColumn: 
                name: author_id
                referencedColumnName: id
    oneToOne:
        seo:
            targetEntity: BlogBundle\Entity\Seo 
            joinColumn: 
                name: seo_id
                referencedColumnName: id
                nullable: false
            cascade: [persist, remove] # Cascade operation on Doctrine level
            onDelete: RESTRICT # Restriction on database level (Seo can't be deleted without deleting the product too).
    manyToMany:
        tags:
            targetEntity: BlogBundle\Entity\Tag
            joinTable:
                name: posts_tags
                joinColumns:
                    post_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
